---
output:
  sort-results: true
linters-settings:
  goimports:
    local-prefixes: "github.com/authzed/servok"
linters:
  enable:
    - "deadcode"
    - "errcheck"
    - "gofumpt"
    - "goimports"
    - "gosimple"
    - "govet"
    - "ineffassign"
    - "revive"
    - "rowserrcheck"
    - "staticcheck"
    - "structcheck"
    - "typecheck"
    - "unused"
    - "varcheck"
issues:
  exclude-rules:
    - path: "internal/sources/srvrecord"
      linters:
        - "revive"
