---
name: "Release"
on:
  push:
    tags:
      - "*"
permissions:
  contents: "write"
jobs:
  goreleaser:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
        with:
          fetch-depth: 0
      - uses: "docker/login-action@v1"
        with:
          registry: "quay.io"
          username: "${{ secrets.QUAYIO_USER }}"
          password: "${{ secrets.QUAYIO_PASSWORD }}"
      - uses: "docker/login-action@v1"
        with:
          registry: "ghcr.io"
          username: "${{ github.actor }}"
          password: "${{ secrets.GHCR_TOKEN }}"
      - uses: "actions/setup-go@v2"
        with:
          go-version: "^1.17"
      - uses: "docker/setup-qemu-action@v1"
      - uses: "docker/setup-buildx-action@v1"
      - uses: "goreleaser/goreleaser-action@v2"
        with:
          distribution: "goreleaser-pro"
          version: "latest"
          args: "release --rm-dist"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          GORELEASER_KEY: "${{ secrets.GORELEASER_KEY }}"
          GEMFURY_PUSH_TOKEN: "${{ secrets.GEMFURY_PUSH_TOKEN }}"
